name: eduscan
description: AI-powered student face identification and attendance system
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^1.0.7
  provider: ^6.1.2
  http: ^1.2.1
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.66.2
  pdf: ^3.10.8
  open_filex: ^4.3.4
  qr_flutter: ^4.1.0
  audioplayers: ^5.2.1
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/sounds/beep_success.mp3
    - assets/sounds/beep_error.mp3
    - assets/images/logo.png
  uses-material-design: true
