import 'dart:io';
import 'package:intl/intl.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/attendance.dart';
import '../models/student.dart';
import '../utils/date_utils.dart' as du;

class PdfService {
  static Future<void> exportAttendanceReport({
    required List<Map<String, dynamic>> records,
    required String schoolName,
    required String dateFrom,
    required String dateTo,
    String? classFilter,
  }) async {
    final pdf = pw.Document();

    final font = pw.Font.helvetica();
    final boldFont = pw.Font.helveticaBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(schoolName,
                style: pw.TextStyle(font: boldFont, fontSize: 18, color: PdfColors.blue800)),
            pw.Text('Attendance Report',
                style: pw.TextStyle(font: boldFont, fontSize: 14)),
            pw.Text('Period: $dateFrom — $dateTo',
                style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey700)),
            if (classFilter != null)
              pw.Text('Class: $classFilter',
                  style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey700)),
            pw.Divider(),
          ],
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by EduScan',
                style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey)),
            pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey)),
          ],
        ),
        build: (context) => [
          pw.TableHelper.fromTextArray(
            headers: ['Student ID', 'Name', 'Class', 'Date', 'Time In', 'Time Out', 'Duration', 'Status'],
            headerStyle: pw.TextStyle(font: boldFont, fontSize: 9),
            cellStyle: pw.TextStyle(font: font, fontSize: 8),
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerLeft,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
              4: pw.Alignment.center,
              5: pw.Alignment.center,
              6: pw.Alignment.center,
              7: pw.Alignment.center,
            },
            data: records.map((r) {
              final durationMins = r['duration_mins'] as int?;
              String durationLabel = '-';
              if (durationMins != null && durationMins > 0) {
                final h = durationMins ~/ 60;
                final m = durationMins % 60;
                durationLabel = h > 0 ? '${h}h ${m}m' : '${m}m';
              }
              return [
                r['student_id'] ?? '',
                '${r['first_name'] ?? ''} ${r['last_name'] ?? ''}'.trim(),
                '${r['class_grade'] ?? ''}-${r['division'] ?? ''}',
                du.fmtDate(r['date']?.toString()),
                r['time_in'] != null ? du.fmtTimeOfDay(r['time_in'] as String?) : '-',
                r['time_out'] != null ? du.fmtTimeOfDay(r['time_out'] as String?) : '-',
                durationLabel,
                (r['status'] ?? '').toString().toUpperCase(),
              ];
            }).toList(),
          ),
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final file = File('${dir.path}/attendance_$timestamp.pdf');
    await file.writeAsBytes(await pdf.save());
    await OpenFilex.open(file.path);
  }

  static Future<void> exportSummaryReport({
    required Map<String, dynamic> summary,
    required List<Map<String, dynamic>> weeklyStats,
    required List<Map<String, dynamic>> studentReport,
    required DateTime generatedAt,
  }) async {
    final pdf = pw.Document();
    final font = pw.Font.helvetica();
    final boldFont = pw.Font.helveticaBold();
    // generatedAt is the device-local clock (already IST), so format directly.
    final dateFmt = DateFormat('dd-MM-yyyy hh:mm a');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('EduScan — Attendance Summary Report',
                style: pw.TextStyle(font: boldFont, fontSize: 16, color: PdfColors.blue800)),
            pw.Text('Generated: ${dateFmt.format(generatedAt)}',
                style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey700)),
            pw.Divider(),
          ],
        ),
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('EduScan', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey)),
            pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
                style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey)),
          ],
        ),
        build: (_) => [
          pw.SizedBox(height: 8),
          pw.Text('Today\'s Overview',
              style: pw.TextStyle(font: boldFont, fontSize: 12)),
          pw.SizedBox(height: 6),
          pw.Row(children: [
            _summaryCell('Total Students', '${summary['total_students'] ?? 0}', font, boldFont),
            _summaryCell('Present', '${summary['present_today'] ?? 0}', font, boldFont),
            _summaryCell('Absent', '${summary['absent_today'] ?? 0}', font, boldFont),
            _summaryCell('Late', '${summary['late_today'] ?? 0}', font, boldFont),
          ]),
          pw.SizedBox(height: 16),
          if (studentReport.isNotEmpty) ...[
            pw.Text('Student Attendance Summary',
                style: pw.TextStyle(font: boldFont, fontSize: 12)),
            pw.SizedBox(height: 6),
            pw.TableHelper.fromTextArray(
              headers: ['Name', 'Class', 'Present', 'Absent', 'Late', '%'],
              headerStyle: pw.TextStyle(font: boldFont, fontSize: 9),
              cellStyle: pw.TextStyle(font: font, fontSize: 8),
              data: studentReport.map((s) => [
                    '${s['first_name'] ?? ''} ${s['last_name'] ?? ''}'.trim(),
                    '${s['class_grade'] ?? ''}-${s['division'] ?? ''}',
                    '${s['present_days'] ?? 0}',
                    '${s['absent_days'] ?? 0}',
                    '${s['late_days'] ?? 0}',
                    '${(s['attendance_percentage'] as num?)?.toStringAsFixed(1) ?? '0.0'}%',
                  ]).toList(),
            ),
          ],
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(generatedAt);
    final file = File('${dir.path}/summary_report_$timestamp.pdf');
    await file.writeAsBytes(await pdf.save());
    await OpenFilex.open(file.path);
  }

  static pw.Widget _summaryCell(
      String label, String value, pw.Font font, pw.Font boldFont) {
    return pw.Expanded(
      child: pw.Container(
        margin: const pw.EdgeInsets.only(right: 8),
        padding: const pw.EdgeInsets.all(8),
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: PdfColors.grey300),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(value, style: pw.TextStyle(font: boldFont, fontSize: 14, color: PdfColors.blue900)),
            pw.Text(label, style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700)),
          ],
        ),
      ),
    );
  }

  static Future<void> exportStudentReport(Student student, List<Attendance> history) async {
    final pdf = pw.Document();
    final font = pw.Font.helvetica();
    final boldFont = pw.Font.helveticaBold();

    final presentDays = history.where((r) => r.status == 'present').length;
    final percentage = history.isNotEmpty
        ? (presentDays / history.length * 100).toStringAsFixed(1)
        : '0.0';

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Student Attendance Report',
                style: pw.TextStyle(font: boldFont, fontSize: 18, color: PdfColors.blue800)),
            pw.SizedBox(height: 16),
            pw.Text('${student.fullName}',
                style: pw.TextStyle(font: boldFont, fontSize: 14)),
            pw.Text('ID: ${student.id}  |  Class: ${student.classLabel}',
                style: pw.TextStyle(font: font, fontSize: 10)),
            pw.Text('Attendance: $presentDays / ${history.length} days ($percentage%)',
                style: pw.TextStyle(font: font, fontSize: 10)),
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              headers: ['Date', 'Status', 'Time In', 'Time Out', 'Duration'],
              headerStyle: pw.TextStyle(font: boldFont, fontSize: 9),
              cellStyle: pw.TextStyle(font: font, fontSize: 8),
              data: history.map((r) => [
                    du.fmtDate(r.date),
                    r.status.toUpperCase(),
                    r.timeIn != null ? du.fmtTimeOfDay(r.timeIn) : '-',
                    r.timeOut != null ? du.fmtTimeOfDay(r.timeOut) : '-',
                    r.durationLabel,
                  ]).toList(),
            ),
          ],
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/student_${student.id}_attendance.pdf');
    await file.writeAsBytes(await pdf.save());
    await OpenFilex.open(file.path);
  }
}
