services:
  - type: web
    name: eduscan-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_WtykALs7i9NF@ep-crimson-brook-aqxs1ja7-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: eduscan-super-secret-jwt-2024